"""Build the FROZEN golden set — the project's oracle.

CRITICAL DISCIPLINE: every expected value below is HAND-COMPUTED from the
rules, typed as a literal. Nothing here is generated by calculator.py — a
golden set derived from the code under test cannot catch that code's bugs.
The reconcile step (scripts/reconcile_golden.py) then diffs these literals
against the live agent; a disagreement means either a hand-arithmetic slip
(fix the literal) or a real calculator bug (fix the code) — both findings.

Once reconciled and hashed, tests/test_golden.py pins it: the numbers do
not move without a deliberate, reviewed regeneration.

Case fields:
  id, category, trap(bool), payload(structured — bypasses the LLM
  extractor so the frozen set is deterministic/offline), question(NL, for
  the separate provider-dependent extraction eval), expect{...}, rationale.
expect:
  outcome, refund, charge (null where N/A), regime, verified,
  must_cite (BOUND clause ids that must appear), must_ask (substrings a
  NEEDS_INFO answer must contain).
"""

import hashlib
import json
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "golden.json"

# departure anchors
D_MAR = "2026-03-20 18:00"   # pre-Apr-2026 -> R2015 for REG
D_JUN = "2026-06-10 18:00"   # post-Apr-15 -> APR2026 for REG; VB2026 for VBS/AB2


def C(cls, dep, cancel, fare, **kw):
    p = {"fare": fare, "cls": cls, "departure": dep, "cancellation": cancel}
    p.update(kw)
    return p


def E(outcome, refund=None, charge=None, regime=None, verified=None,
      must_cite=(), must_ask=()):
    return {"outcome": outcome, "refund": refund, "charge": charge,
            "regime": regime, "verified": verified,
            "must_cite": list(must_cite), "must_ask": list(must_ask)}


R6 = ["2015/rule-6"]
R9 = ["2015/rule-9"]

# ---- self-contained NL question generator (Day 9) ----
# Each question must carry an ABSOLUTE departure datetime and enough to
# derive the cancellation time, so the extraction eval measures extraction
# rather than penalizing under-specified prompts. Cancellation is phrased
# as "right now" with the per-case reference time (now) set to the
# cancellation instant — the natural framing ("I'm cancelling now").
CLS_HUMAN = {"1A": "First AC (1A)", "EC": "Executive Chair Car",
             "2A": "2nd AC (2A)", "FC": "First Class",
             "3A": "3rd AC (3A)", "CC": "AC Chair Car",
             "3E": "AC 3-Economy", "SL": "Sleeper", "2S": "Second Sitting"}
TRAIN_HUMAN = {"REG": "a regular Mail/Express", "VBS": "a Vande Bharat Sleeper",
               "AB2": "an Amrit Bharat 2.0 train"}
STATUS_HUMAN = {"CNF": "confirmed", "RAC": "RAC", "WL": "waitlisted"}
QUOTA_HUMAN = {"GN": "", "TQ": "Tatkal ", "PT": "Premium Tatkal "}


def _human_dt(s: str) -> str:
    try:
        dt = datetime.fromisoformat(s.replace("T", " "))
    except ValueError:
        return s
    if len(s) <= 10:                       # date only — deliberately no time
        return dt.strftime("%-d %b %Y")
    return dt.strftime("%-d %b %Y, %-I:%M %p")


def make_question(p: dict) -> str:
    cls = p.get("cls") or p.get("class")
    cls_h = CLS_HUMAN.get(cls, f"{cls} class") if cls else "a reserved"
    train_h = TRAIN_HUMAN.get(p.get("train_type", "REG"), p.get("train_type"))
    status_h = STATUS_HUMAN.get(p.get("status", "CNF"), "")
    quota_h = QUOTA_HUMAN.get(p.get("quota", "GN"), "")
    book = {"E": "booked online", "C": "booked at the counter"}[p.get("channel", "E")]
    ticket = f"{status_h} {quota_h}{cls_h} ticket".replace("  ", " ").strip()
    if p.get("fare") is not None:
        ticket += f" for ₹{p['fare']}"
    dep = _human_dt(p["departure"])
    q = f"I have a {ticket}, {book}, on {train_h} departing {dep}."
    if p.get("chart_prepared"):
        q += " The chart is already prepared."
    disr = p.get("disruption", "NONE")
    if disr == "TRAIN_CANCELLED":
        q += " The railways have now cancelled the train — what refund am I due?"
    elif disr == "DELAY_GT_3H":
        q += (" It is running more than 3 hours late and I travelled anyway"
              if p.get("travelled") else
              " It is running more than 3 hours late and I decided not to travel")
        q += " — what refund am I due?"
    else:
        q += " I want to cancel it right now — what refund am I due?"
    return q

CASES = [
    # ---------------- R2015 CNF general quota ----------------
    dict(id="r2015-3a-60h", category="R2015-CNF", trap=False,
         payload=C("3A", D_MAR, "2026-03-18 06:00", 1500),
         question="3AC ticket Rs1500, regular train 20 Mar 6pm, cancelling 18 Mar 6am.",
         expect=E("COMPUTED", 1320, 180, "R2015", True, R6),
         rationale="60h>48h: flat charge Rs180 (rule 6(a)); 1500-180=1320."),
    dict(id="r2015-3a-48h", category="R2015-CNF", trap=True,
         payload=C("3A", D_MAR, "2026-03-18 18:00", 1500),
         question="3AC Rs1500, cancelling exactly 48 hours before a regular train.",
         expect=E("COMPUTED", 1125, 375, "R2015", True, R6),
         rationale="48h is NOT >48h: falls to 25% band. max(375,180)=375; refund 1125."),
    dict(id="r2015-3a-36h", category="R2015-CNF", trap=False,
         payload=C("3A", D_MAR, "2026-03-19 06:00", 1500),
         question="3AC Rs1500, cancelling 36h before a regular train.",
         expect=E("COMPUTED", 1125, 375, "R2015", True, R6),
         rationale="12<36<=48: 25%. max(375,180)=375; refund 1125."),
    dict(id="r2015-3a-12h", category="R2015-CNF", trap=True,
         payload=C("3A", D_MAR, "2026-03-20 06:00", 1500),
         question="3AC Rs1500, cancelling exactly 12 hours before.",
         expect=E("COMPUTED", 750, 750, "R2015", True, R6),
         rationale="12h is NOT >12h: 50% band. max(750,180)=750; refund 750."),
    dict(id="r2015-3a-10h", category="R2015-CNF", trap=False,
         payload=C("3A", D_MAR, "2026-03-20 08:00", 1500),
         question="3AC Rs1500, cancelling 10h before.",
         expect=E("COMPUTED", 750, 750, "R2015", True, R6),
         rationale="4<10<=12: 50%. max(750,180)=750; refund 750."),
    dict(id="r2015-3a-4h", category="R2015-CNF", trap=True,
         payload=C("3A", D_MAR, "2026-03-20 14:00", 1500),
         question="3AC Rs1500, cancelling exactly 4 hours before.",
         expect=E("NO_REFUND", 0, 1500, "R2015", True, R6),
         rationale="4h is NOT >4h: no refund inside the 4h window."),
    dict(id="r2015-3a-2h", category="R2015-CNF", trap=False,
         payload=C("3A", D_MAR, "2026-03-20 16:00", 1500),
         question="3AC Rs1500, cancelling 2h before.",
         expect=E("NO_REFUND", 0, 1500, "R2015", True, R6),
         rationale="<4h: no refund."),
    dict(id="r2015-sl-60h", category="R2015-CNF", trap=False,
         payload=C("SL", D_MAR, "2026-03-18 06:00", 500),
         question="Sleeper Rs500, cancelling 60h before.",
         expect=E("COMPUTED", 380, 120, "R2015", True, R6),
         rationale=">48h: flat Rs120; refund 380."),
    dict(id="r2015-sl-36h", category="R2015-CNF", trap=False,
         payload=C("SL", D_MAR, "2026-03-19 06:00", 500),
         question="Sleeper Rs500, cancelling 36h before.",
         expect=E("COMPUTED", 375, 125, "R2015", True, R6),
         rationale="25% band: max(125,120)=125; refund 375."),
    dict(id="r2015-sl-300-36h", category="R2015-CNF", trap=True,
         payload=C("SL", D_MAR, "2026-03-19 06:00", 300),
         question="Sleeper Rs300, cancelling 36h before.",
         expect=E("COMPUTED", 180, 120, "R2015", True, R6),
         rationale="TRAP flat binds: 25%=Rs75 < flat Rs120, so Rs120 charged; refund 180."),
    dict(id="r2015-2s-100-36h", category="R2015-CNF", trap=True,
         payload=C("2S", D_MAR, "2026-03-19 06:00", 100),
         question="Second sitting Rs100, cancelling 36h before.",
         expect=E("COMPUTED", 40, 60, "R2015", True, R6),
         rationale="TRAP flat binds: 25%=Rs25 < flat Rs60; refund 40."),
    dict(id="r2015-2s-50-60h", category="R2015-CNF", trap=True,
         payload=C("2S", D_MAR, "2026-03-18 06:00", 50),
         question="Second sitting Rs50, cancelling 60h before.",
         expect=E("NO_REFUND", 0, 50, "R2015", True, R6),
         rationale="TRAP flat>fare: flat Rs60 exceeds Rs50 fare; charge capped at fare; no refund."),
    dict(id="r2015-sl-120-60h", category="R2015-CNF", trap=True,
         payload=C("SL", D_MAR, "2026-03-18 06:00", 120),
         question="Sleeper Rs120, cancelling 60h before.",
         expect=E("NO_REFUND", 0, 120, "R2015", True, R6),
         rationale="TRAP flat==fare boundary: flat Rs120 equals fare; no refund."),
    dict(id="r2015-1a-5000-60h", category="R2015-CNF", trap=False,
         payload=C("1A", D_MAR, "2026-03-18 06:00", 5000),
         question="First AC Rs5000, cancelling 60h before.",
         expect=E("COMPUTED", 4760, 240, "R2015", True, R6),
         rationale=">48h: flat Rs240; refund 4760 (GST on charge extra, not computed)."),
    dict(id="r2015-1a-5000-36h", category="R2015-CNF", trap=False,
         payload=C("1A", D_MAR, "2026-03-19 06:00", 5000),
         question="First AC Rs5000, cancelling 36h before.",
         expect=E("COMPUTED", 3750, 1250, "R2015", True, R6),
         rationale="25%: max(1250,240)=1250; refund 3750."),
    dict(id="r2015-ec-2000-10h", category="R2015-CNF", trap=False,
         payload=C("EC", D_MAR, "2026-03-20 08:00", 2000),
         question="Executive chair car Rs2000, cancelling 10h before.",
         expect=E("COMPUTED", 1000, 1000, "R2015", True, R6),
         rationale="50%: max(1000,240)=1000; refund 1000."),
    dict(id="r2015-2a-2400-60h", category="R2015-CNF", trap=False,
         payload=C("2A", D_MAR, "2026-03-18 06:00", 2400),
         question="2AC Rs2400, cancelling 60h before.",
         expect=E("COMPUTED", 2200, 200, "R2015", True, R6),
         rationale=">48h: flat Rs200; refund 2200."),
    dict(id="r2015-cc-1200-36h", category="R2015-CNF", trap=False,
         payload=C("CC", D_MAR, "2026-03-19 06:00", 1200),
         question="Chair car Rs1200, cancelling 36h before.",
         expect=E("COMPUTED", 900, 300, "R2015", True, R6),
         rationale="25%: max(300,180)=300; refund 900."),
    dict(id="r2015-3e-800-60h", category="R2015-CNF", trap=False,
         payload=C("3E", D_MAR, "2026-03-18 06:00", 800),
         question="AC 3 economy Rs800, cancelling 60h before.",
         expect=E("COMPUTED", 620, 180, "R2015", True, R6),
         rationale=">48h: flat Rs180; refund 620."),
    dict(id="r2015-fc-1000-10h", category="R2015-CNF", trap=False,
         payload=C("FC", D_MAR, "2026-03-20 08:00", 1000),
         question="First class Rs1000, cancelling 10h before.",
         expect=E("COMPUTED", 500, 500, "R2015", True, R6),
         rationale="50%: max(500,200)=500; refund 500."),
    dict(id="r2015-2s-500-36h", category="R2015-CNF", trap=False,
         payload=C("2S", D_MAR, "2026-03-19 06:00", 500),
         question="Second sitting Rs500, cancelling 36h before.",
         expect=E("COMPUTED", 375, 125, "R2015", True, R6),
         rationale="25%: max(125,60)=125; refund 375."),
    dict(id="r2015-sl-400-48h", category="R2015-CNF", trap=True,
         payload=C("SL", D_MAR, "2026-03-18 18:00", 400),
         question="Sleeper Rs400, cancelling exactly 48h before.",
         expect=E("COMPUTED", 280, 120, "R2015", True, R6),
         rationale="TRAP boundary+flat: 48h->25% band; 25%=Rs100<flat120; refund 280."),
    dict(id="r2015-2a-2400-13h", category="R2015-CNF", trap=False,
         payload=C("2A", D_MAR, "2026-03-20 05:00", 2400),
         question="2AC Rs2400, cancelling 13h before.",
         expect=E("COMPUTED", 1800, 600, "R2015", True, R6),
         rationale="13h>12: 25% band; max(600,200)=600; refund 1800."),

    # ---------------- R2015 Tatkal / Premium Tatkal ----------------
    dict(id="r2015-tq-3a-36h", category="R2015-TATKAL", trap=False,
         payload=C("3A", D_MAR, "2026-03-19 06:00", 1500, quota="TQ"),
         question="Confirmed Tatkal 3AC Rs1500, cancelling 36h before.",
         expect=E("NO_REFUND", 0, 1500, "R2015", True),
         rationale="Confirmed Tatkal: no refund on cancellation."),
    dict(id="r2015-pt-2a-60h", category="R2015-TATKAL", trap=False,
         payload=C("2A", D_MAR, "2026-03-18 06:00", 2400, quota="PT"),
         question="Confirmed Premium Tatkal 2AC Rs2400, cancelling 60h before.",
         expect=E("NO_REFUND", 0, 2400, "R2015", True),
         rationale="Confirmed Premium Tatkal: no refund; dynamic fare forfeited."),

    # ---------------- R2015 RAC / WL ----------------
    dict(id="r2015-wl-sl-900-e-20h", category="R2015-RACWL", trap=False,
         payload=C("SL", D_MAR, "2026-03-19 22:00", 900, status="WL", channel="E"),
         question="Waitlisted sleeper e-ticket Rs900, cancelling 20h before.",
         expect=E("COMPUTED", 840, 60, "R2015", True),
         rationale="RAC/WL: fare less clerkage Rs60; refund 840 (WL e-ticket auto-cancels at chart)."),
    dict(id="r2015-rac-3a-1500-e-20h", category="R2015-RACWL", trap=False,
         payload=C("3A", D_MAR, "2026-03-19 22:00", 1500, status="RAC", channel="E"),
         question="RAC 3AC e-ticket Rs1500, cancelling 20h before.",
         expect=E("COMPUTED", 1440, 60, "R2015", True),
         rationale="RAC: fare less clerkage Rs60; refund 1440 (RAC not auto-cancelled)."),
    dict(id="r2015-wl-sl-900-20min", category="R2015-RACWL", trap=True,
         payload=C("SL", D_MAR, "2026-03-20 17:40", 900, status="WL", channel="E"),
         question="Waitlisted sleeper Rs900, cancelling 20 minutes before departure.",
         expect=E("NO_REFUND", 0, 900, "R2015", True),
         rationale="TRAP: past the 30-minute RAC/WL cutoff; no refund."),
    dict(id="r2015-rac-2s-100-c-40h", category="R2015-RACWL", trap=False,
         payload=C("2S", D_MAR, "2026-03-19 02:00", 100, status="RAC", channel="C"),
         question="RAC second-sitting counter ticket Rs100, cancelling 40h before.",
         expect=E("COMPUTED", 40, 60, "R2015", True),
         rationale="RAC: fare 100 less clerkage 60; refund 40."),
    dict(id="r2015-wl-pt-esc", category="R2015-RACWL", trap=True,
         payload=C("3A", D_MAR, "2026-03-19 22:00", 1500, status="WL", quota="PT"),
         question="Waitlisted Premium Tatkal 3AC, cancelling 20h before.",
         expect=E("ESCALATE", None, None, "R2015", False),
         rationale="TRAP: Premium Tatkal issues only CNF/RAC; WL+PT needs manual review."),
    dict(id="r2015-rac-pt-2000-e-20h", category="R2015-RACWL", trap=True,
         payload=C("2A", D_MAR, "2026-03-19 22:00", 2000, status="RAC", quota="PT", channel="E"),
         question="RAC Premium Tatkal 2AC e-ticket Rs2000, cancelling 20h before.",
         expect=E("COMPUTED", 1940, 60, "R2015", True),
         rationale="TRAP: RAC+PT is valid (PT issues CNF/RAC); clerkage path applies; refund 1940."),
    dict(id="r2015-rac-sl-500-e-25min", category="R2015-RACWL", trap=True,
         payload=C("SL", D_MAR, "2026-03-20 17:35", 500, status="RAC", channel="E"),
         question="RAC sleeper Rs500, cancelling 25 minutes before departure.",
         expect=E("NO_REFUND", 0, 500, "R2015", True),
         rationale="TRAP: 25min < 30min cutoff; no refund."),

    # ---------------- Disruption (any regime) ----------------
    dict(id="r2015-cancelled-e-sl-900", category="DISRUPTION", trap=False,
         payload=C("SL", D_MAR, "2026-03-19 10:00", 900, disruption="TRAIN_CANCELLED", channel="E"),
         question="Railways cancelled my sleeper train, e-ticket Rs900.",
         expect=E("COMPUTED", 900, 0, "R2015", True, R9),
         rationale="Train cancelled: full refund (rule 9); e-ticket auto."),
    dict(id="r2015-cancelled-c-2a-2400", category="DISRUPTION", trap=False,
         payload=C("2A", D_MAR, "2026-03-19 10:00", 2400, disruption="TRAIN_CANCELLED", channel="C"),
         question="Railways cancelled my train, counter 2AC ticket Rs2400.",
         expect=E("COMPUTED", 2400, 0, "R2015", True, R9),
         rationale="Train cancelled: full refund; surrender at counter within 72h."),
    dict(id="r2015-delay-e-3a-1500", category="DISRUPTION", trap=False,
         payload=C("3A", D_MAR, "2026-03-20 12:00", 1500, disruption="DELAY_GT_3H", channel="E"),
         question="Train delayed over 3 hours, didn't travel, 3AC e-ticket Rs1500.",
         expect=E("COMPUTED", 1500, 0, "R2015", True),
         rationale="Late >3h and not travelled: full refund; TDR before ACTUAL departure."),
    dict(id="r2015-delay-travelled", category="DISRUPTION", trap=True,
         payload=C("SL", D_MAR, "2026-03-20 12:00", 900, disruption="DELAY_GT_3H", travelled=True),
         question="Train was 4 hours late but I travelled anyway, sleeper Rs900.",
         expect=E("ESCALATE", None, None, "R2015", False),
         rationale="TRAP: travelled despite delay; partial-journey claims out of scope."),
    dict(id="r2015-tq-cancelled", category="DISRUPTION", trap=True,
         payload=C("3A", D_MAR, "2026-03-19 10:00", 1500, quota="TQ", disruption="TRAIN_CANCELLED"),
         question="Confirmed Tatkal 3AC Rs1500 but the railways cancelled the train.",
         expect=E("COMPUTED", 1500, 0, "R2015", True, R9),
         rationale="TRAP: disruption overrides the Tatkal no-refund rule; full refund."),
    dict(id="r2015-cancelled-tq-c", category="DISRUPTION", trap=True,
         payload=C("2A", D_MAR, "2026-03-19 10:00", 2400, quota="TQ", disruption="TRAIN_CANCELLED", channel="C"),
         question="Counter Tatkal 2AC Rs2400, train cancelled by railways.",
         expect=E("COMPUTED", 2400, 0, "R2015", True, R9),
         rationale="TRAP: Tatkal + counter + train cancelled -> full refund."),

    # ---------------- Chart prepared ----------------
    dict(id="r2015-chart-cnf", category="CHART", trap=True,
         payload=C("3A", D_MAR, "2026-03-20 08:00", 1500, chart_prepared=True),
         question="Confirmed 3AC Rs1500, chart already prepared, cancelling 10h before.",
         expect=E("ESCALATE", None, None, "R2015", False),
         rationale="TRAP: post-chart CNF cancellation routes via TDR; out of verified scope."),
    dict(id="r2015-chart-wl", category="CHART", trap=True,
         payload=C("SL", D_MAR, "2026-03-19 22:00", 900, status="WL", channel="E", chart_prepared=True),
         question="Waitlisted sleeper Rs900, chart prepared, cancelling 20h before.",
         expect=E("COMPUTED", 840, 60, "R2015", True),
         rationale="TRAP: RAC/WL handled before the chart gate; clerkage path still applies; refund 840."),

    # ---------------- VB2026 (Vande Bharat Sleeper / Amrit Bharat 2.0) ----------------
    dict(id="vb-2a-2400-102h", category="VB2026", trap=False,
         payload=C("2A", D_JUN, "2026-06-06 12:00", 2400, train_type="VBS"),
         question="Vande Bharat Sleeper 2AC Rs2400, cancelling 102h before.",
         expect=E("COMPUTED", 1800, 600, "VB2026", True, ["jan2026/6(4)(a)"]),
         rationale=">72h: 25% (rule 6(4)(a)); refund 1800. No flat-only band on these trains."),
    dict(id="vb-2a-2400-72h", category="VB2026", trap=True,
         payload=C("2A", D_JUN, "2026-06-07 18:00", 2400, train_type="VBS"),
         question="Vande Bharat Sleeper 2AC Rs2400, cancelling exactly 72h before.",
         expect=E("COMPUTED", 1200, 1200, "VB2026", True, ["jan2026/6(4)(b)"]),
         rationale="TRAP: 72h NOT >72h -> 50% (rule 6(4)(b)); refund 1200."),
    dict(id="vb-2a-2400-36h", category="VB2026", trap=False,
         payload=C("2A", D_JUN, "2026-06-09 06:00", 2400, train_type="VBS"),
         question="Vande Bharat Sleeper 2AC Rs2400, cancelling 36h before.",
         expect=E("COMPUTED", 1200, 1200, "VB2026", True, ["jan2026/6(4)(b)"]),
         rationale="8<36<=72: 50%; refund 1200."),
    dict(id="vb-sl-1000-4h", category="VB2026", trap=False,
         payload=C("SL", D_JUN, "2026-06-10 14:00", 1000, train_type="VBS"),
         question="Vande Bharat Sleeper SL Rs1000, cancelling 4h before.",
         expect=E("NO_REFUND", 0, 1000, "VB2026", True, ["jan2026/6(4)(c)"]),
         rationale="<8h: no refund (rule 6(4)(c))."),
    dict(id="vb-8h-exact", category="VB2026", trap=True,
         payload=C("SL", D_JUN, "2026-06-10 10:00", 1000, train_type="VBS"),
         question="Vande Bharat Sleeper SL Rs1000, cancelling exactly 8h before.",
         expect=E("NO_REFUND", 0, 1000, "VB2026", True, ["jan2026/6(4)(c)"]),
         rationale="TRAP: 8h NOT >8h -> no refund."),
    dict(id="ab2-3a-1500-102h", category="VB2026", trap=False,
         payload=C("3A", D_JUN, "2026-06-06 12:00", 1500, train_type="AB2"),
         question="Amrit Bharat 2.0 3AC Rs1500, cancelling 102h before.",
         expect=E("COMPUTED", 1125, 375, "VB2026", True, ["jan2026/6(4)(a)"]),
         rationale=">72h: 25%; refund 1125."),
    dict(id="vb-1a-4000-102h", category="VB2026", trap=False,
         payload=C("1A", D_JUN, "2026-06-06 12:00", 4000, train_type="VBS"),
         question="Vande Bharat Sleeper 1AC Rs4000, cancelling 102h before.",
         expect=E("COMPUTED", 3000, 1000, "VB2026", True, ["jan2026/6(4)(a)"]),
         rationale=">72h: 25%=1000; refund 3000."),
    dict(id="ab2-sl-1000-72h", category="VB2026", trap=True,
         payload=C("SL", D_JUN, "2026-06-07 18:00", 1000, train_type="AB2"),
         question="Amrit Bharat 2.0 SL Rs1000, cancelling exactly 72h before.",
         expect=E("COMPUTED", 500, 500, "VB2026", True, ["jan2026/6(4)(b)"]),
         rationale="TRAP: 72h -> 50%; refund 500."),
    dict(id="vb-tq-2400-36h", category="VB2026", trap=True,
         payload=C("2A", D_JUN, "2026-06-09 06:00", 2400, train_type="VBS", quota="TQ"),
         question="Tatkal Vande Bharat Sleeper 2AC Rs2400, cancelling 36h before.",
         expect=E("NO_REFUND", 0, 2400, "VB2026", True),
         rationale="TRAP: Tatkal no-refund gate applies before the VB tiers."),
    dict(id="vb-rac-2400-e-36h", category="VB2026", trap=True,
         payload=C("2A", D_JUN, "2026-06-09 06:00", 2400, train_type="VBS", status="RAC", channel="E"),
         question="RAC Vande Bharat Sleeper 2AC e-ticket Rs2400, cancelling 36h before.",
         expect=E("COMPUTED", 2340, 60, "VB2026", True),
         rationale="TRAP: RAC clerkage (Rs60) is regime-independent, even on VB; refund 2340."),
    dict(id="vb-wl-2400-e-20h", category="VB2026", trap=False,
         payload=C("2A", D_JUN, "2026-06-09 22:00", 2400, train_type="VBS", status="WL", channel="E"),
         question="Waitlisted Vande Bharat Sleeper 2AC Rs2400, cancelling 20h before.",
         expect=E("COMPUTED", 2340, 60, "VB2026", True),
         rationale="WL clerkage Rs60; refund 2340."),
    dict(id="vb-cancelled-2400", category="VB2026", trap=False,
         payload=C("2A", D_JUN, "2026-06-09 10:00", 2400, train_type="VBS", disruption="TRAIN_CANCELLED", channel="E"),
         question="Railways cancelled my Vande Bharat Sleeper, 2AC Rs2400.",
         expect=E("COMPUTED", 2400, 0, "VB2026", True, R9),
         rationale="Train cancelled: full refund even on VB."),
    dict(id="vb-oos-jan", category="VB2026", trap=True,
         payload=C("2A", "2026-02-01 18:00", "2026-01-10 12:00", 2400, train_type="VBS"),
         question="Vande Bharat Sleeper 2AC, cancelling 10 Jan 2026 (before the new rules).",
         expect=E("ESCALATE", None, None, "UNDETERMINED", False),
         rationale="TRAP: cancellation predates the 16.01.2026 VB regime; out of scope."),

    # ---------------- APR2026 (all-trains reform; primary pending) ----------------
    dict(id="apr-3a-102h", category="APR2026", trap=True,
         payload=C("3A", D_JUN, "2026-06-06 12:00", 1500),
         question="Regular 3AC Rs1500, June 10 6pm, cancelling 102h before.",
         expect=E("ESCALATE", None, None, "APR2026", False),
         rationale="TRAP: >72h tier is flat-only; Apr-2026 flats UNVERIFIED -> escalate."),
    dict(id="apr-2a-2400-102h", category="APR2026", trap=True,
         payload=C("2A", D_JUN, "2026-06-06 12:00", 2400),
         question="Regular 2AC Rs2400, cancelling 102h before (June).",
         expect=E("ESCALATE", None, None, "APR2026", False),
         rationale="TRAP: >72h flat-only tier under unverified flats -> escalate."),
    dict(id="apr-72h-exact", category="APR2026", trap=True,
         payload=C("3A", D_JUN, "2026-06-07 18:00", 1500),
         question="Regular 3AC Rs1500, cancelling exactly 72h before (June).",
         expect=E("COMPUTED", 1125, 375, "APR2026", False),
         rationale="TRAP: 72h NOT >72h -> 25% tier; 25%=375>flat180 so amount is safe; refund 1125."),
    dict(id="apr-3a-36h", category="APR2026", trap=False,
         payload=C("3A", D_JUN, "2026-06-09 06:00", 1500),
         question="Regular 3AC Rs1500, cancelling 36h before (June).",
         expect=E("COMPUTED", 1125, 375, "APR2026", False),
         rationale="24<36<=72: 25%=375>flat180; refund 1125 (provisional, primary pending)."),
    dict(id="apr-sl-300-36h", category="APR2026", trap=True,
         payload=C("SL", D_JUN, "2026-06-09 06:00", 300),
         question="Regular sleeper Rs300, cancelling 36h before (June).",
         expect=E("ESCALATE", None, None, "APR2026", False),
         rationale="TRAP: 25%=Rs75 does not exceed claimed flat Rs120; flat-decided -> escalate."),
    dict(id="apr-3a-12h", category="APR2026", trap=False,
         payload=C("3A", D_JUN, "2026-06-10 06:00", 1500),
         question="Regular 3AC Rs1500, cancelling 12h before (June).",
         expect=E("COMPUTED", 750, 750, "APR2026", False),
         rationale="8<12<=24: 50%=750>flat180; refund 750 (provisional)."),
    dict(id="apr-sl-200-12h", category="APR2026", trap=True,
         payload=C("SL", D_JUN, "2026-06-10 06:00", 200),
         question="Regular sleeper Rs200, cancelling 12h before (June).",
         expect=E("ESCALATE", None, None, "APR2026", False),
         rationale="TRAP: 50%=Rs100 does not exceed claimed flat Rs120; flat-decided -> escalate."),
    dict(id="apr-3a-4h", category="APR2026", trap=False,
         payload=C("3A", D_JUN, "2026-06-10 14:00", 1500),
         question="Regular 3AC Rs1500, cancelling 4h before (June).",
         expect=E("NO_REFUND", 0, 1500, "APR2026", False),
         rationale="<8h: no refund (tier confirmed by announcement; primary pending)."),
    dict(id="apr-1a-5000-36h", category="APR2026", trap=False,
         payload=C("1A", D_JUN, "2026-06-09 06:00", 5000),
         question="Regular first AC Rs5000, cancelling 36h before (June).",
         expect=E("COMPUTED", 3750, 1250, "APR2026", False),
         rationale="25%=1250>flat240; refund 3750 (provisional)."),
    dict(id="apr-tq-36h", category="APR2026", trap=False,
         payload=C("3A", D_JUN, "2026-06-09 06:00", 1500, quota="TQ"),
         question="Confirmed Tatkal 3AC Rs1500, cancelling 36h before (June).",
         expect=E("NO_REFUND", 0, 1500, "APR2026", True),
         rationale="Tatkal no-refund gate is verified and regime-independent."),
    dict(id="apr-cancelled", category="APR2026", trap=False,
         payload=C("3A", D_JUN, "2026-06-09 10:00", 1500, disruption="TRAIN_CANCELLED", channel="E"),
         question="Railways cancelled my regular train (June), 3AC Rs1500.",
         expect=E("COMPUTED", 1500, 0, "APR2026", True, R9),
         rationale="Train cancelled: full refund, verified, even under the pending regime."),
    dict(id="apr-rollout", category="APR2026", trap=True,
         payload=C("3A", "2026-04-20 18:00", "2026-04-10 10:00", 1500),
         question="Regular 3AC Rs1500, cancelling 10 Apr 2026 (during the phased rollout).",
         expect=E("ESCALATE", None, None, "UNDETERMINED", False),
         rationale="TRAP: cancellation inside the 1-15 Apr rollout window; regime undetermined."),

    # ---------------- Intake: NEEDS_INFO / out of scope ----------------
    dict(id="ni-unreserved", category="NEEDS_INFO", trap=True,
         payload=C("unreserved", D_MAR, "2026-03-19 06:00", 100),
         question="Unreserved ticket Rs100, cancelling 36h before.",
         expect=E("NEEDS_INFO", None, None, None, None, must_ask=["unreserved"]),
         rationale="TRAP: unreserved is outside reserved-ticket rules; ask, don't guess 2S."),
    dict(id="ni-amrit-bharat", category="NEEDS_INFO", trap=True,
         payload=C("SL", D_MAR, "2026-03-19 06:00", 1000, train_type="Amrit Bharat"),
         question="Amrit Bharat sleeper Rs1000, cancelling 36h before.",
         expect=E("NEEDS_INFO", None, None, None, None, must_ask=["2.0"]),
         rationale="TRAP: plain 'Amrit Bharat' is ambiguous (2.0 vs original); ask which."),
    dict(id="ni-missing-fare", category="NEEDS_INFO", trap=False,
         payload={"cls": "3A", "departure": D_MAR, "cancellation": "2026-03-19 06:00"},
         question="3AC ticket cancelling 36h before, not sure of the fare.",
         expect=E("NEEDS_INFO", None, None, None, None, must_ask=["fare"]),
         rationale="Fare is required; ask for it."),
    dict(id="ni-bad-class", category="NEEDS_INFO", trap=False,
         payload=C("4A", D_MAR, "2026-03-19 06:00", 1000),
         question="4A class ticket Rs1000, cancelling 36h before.",
         expect=E("NEEDS_INFO", None, None, None, None, must_ask=["4A"]),
         rationale="Unknown class code; ask (no 4A class exists)."),
    dict(id="ni-date-no-time", category="NEEDS_INFO", trap=False,
         payload={"fare": 1000, "cls": "SL", "departure": "2026-03-20", "cancellation": "2026-03-19 10:00"},
         question="Sleeper Rs1000 leaving 20 March, cancelled 19 March 10am.",
         expect=E("NEEDS_INFO", None, None, None, None, must_ask=["time of day"]),
         rationale="Departure has no clock time; tiers are hour-sensitive; ask."),
]


def main():
    ids = [c["id"] for c in CASES]
    assert len(ids) == len(set(ids)), "duplicate case ids"
    # regenerate self-contained questions + set per-case reference time so
    # "cancel right now" resolves to the exact cancellation instant
    for c in CASES:
        c["question"] = make_question(c["payload"])
        c["now"] = c["payload"]["cancellation"]
    payload = json.dumps(CASES, indent=2, ensure_ascii=False, sort_keys=True)
    digest = hashlib.sha256(payload.encode()).hexdigest()
    doc = {"meta": {"version": 1, "n_cases": len(CASES),
                    "n_traps": sum(c["trap"] for c in CASES),
                    "sha256": digest,
                    "note": "FROZEN oracle — expected values hand-computed, "
                            "not generated by calculator.py. See "
                            "scripts/build_golden.py."},
           "cases": CASES}
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(doc, indent=2, ensure_ascii=False))
    print(f"wrote {len(CASES)} cases ({doc['meta']['n_traps']} traps) -> {OUT}")
    print(f"sha256(cases) = {digest}")


if __name__ == "__main__":
    main()
